create or replace procedure DIENTES.ADD_TIPOSANGRE(NOMBRE IN VARCHAR2)
IS
id_sangre number;
BEGIN
id_sangre := DIENTES.TIPO_SANGRE_SQ.NEXTVAL;

INSERT INTO DIENTES.TIPO_SANGRE (ID_TIPO_SANGRE, NOMBRE)
     VALUES (id_sangre, NOMBRE);
 END;
 
create or replace procedure DIENTES.SELECT_TIPOSANGRE(SALIDA OUT SYS_REFCURSOR)
AS
BEGIN
OPEN SALIDA FOR SELECT * FROM DIENTES.TIPO_SANGRE;
 END;