ALTER TABLE DIENTES.ABONOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.ABONOS CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.ABONOS
(
  ID_ABONOS                NUMBER               NOT NULL,
  PAGADO                   NUMBER               DEFAULT 0                     NOT NULL,
  ID_TRATAMIENTO_PACIENTE  NUMBER               NOT NULL,
  COSTO                    NUMBER               NOT NULL,
  FECHA                    DATE,
  ID_PAGO                  NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DIENTES.ABONOS_PK ON DIENTES.ABONOS
(ID_ABONOS)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DIENTES.ABONOS ADD (
  CONSTRAINT ABONOS_PK
  PRIMARY KEY
  (ID_ABONOS)
  USING INDEX DIENTES.ABONOS_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.ABONOS ADD (
  CONSTRAINT ABONOS_R01 
  FOREIGN KEY (ID_TRATAMIENTO_PACIENTE) 
  REFERENCES DIENTES.TRATAMIENTO_PACIENTE
  ENABLE VALIDATE,
  CONSTRAINT ABONOS_R02 
  FOREIGN KEY (ID_PAGO) 
  REFERENCES DIENTES.PAGOS
  ENABLE VALIDATE);
