ALTER TABLE DIENTES.ALERGIAS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.ALERGIAS CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.ALERGIAS
(
  ID_ALERGIA  INTEGER                           NOT NULL,
  NOMBRE      VARCHAR2(100 BYTE)                NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.ENFERMEDADES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.ENFERMEDADES CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.ENFERMEDADES
(
  ID_ENFERMEDAD  INTEGER,
  NOMBRE         VARCHAR2(100 BYTE)             NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.ESPECIALIDADES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.ESPECIALIDADES CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.ESPECIALIDADES
(
  ID_ESPECIALIDAD  INTEGER,
  NOMBRE           VARCHAR2(100 BYTE)           NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.GRUPOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.GRUPOS CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.GRUPOS
(
  ID_GRUPO  INTEGER,
  NOMBRE    VARCHAR2(100 BYTE)                  NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.MATERIAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.MATERIAL CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.MATERIAL
(
  ID_MATERIAL  INTEGER,
  NOMBRE       VARCHAR2(100 BYTE)               NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.MONEDAS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.MONEDAS CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.MONEDAS
(
  ID_MONEDA  INTEGER,
  SIGLAS     VARCHAR2(3 BYTE)                   NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.PAISES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.PAISES CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.PAISES
(
  ID_PAIS  INTEGER,
  NOMBRE   VARCHAR2(100 BYTE)                   NOT NULL,
  SIGLAS   VARCHAR2(3 BYTE)                     NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.PERMISO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.PERMISO CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.PERMISO
(
  ID_PERMISO  INTEGER,
  NOMBRE      VARCHAR2(100 BYTE)                NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.TIPO_PAGOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.TIPO_PAGOS CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.TIPO_PAGOS
(
  ID_TIPOPAGOS  INTEGER,
  NOMBRE        VARCHAR2(100 BYTE)              NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.TRATAMIENTO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.TRATAMIENTO CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.TRATAMIENTO
(
  ID_TRATAMIENTO   INTEGER,
  NOMBRE           VARCHAR2(100 BYTE)           NOT NULL,
  COSTO            LONG                         NOT NULL,
  ID_ESPECIALIDAD  INTEGER                      NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE DIENTES.TRATAMIENTO_MATERIAL CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.TRATAMIENTO_MATERIAL
(
  ID_TRATAMIENTO  INTEGER                       NOT NULL,
  ID_MATERIAL     INTEGER                       NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DIENTES.ALERGIAS_PK ON DIENTES.ALERGIAS
(ID_ALERGIA)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.ENFERMEDADES_PK ON DIENTES.ENFERMEDADES
(ID_ENFERMEDAD)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.ESPECIALIDADES_PK ON DIENTES.ESPECIALIDADES
(ID_ESPECIALIDAD)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.GRUPOS_PK ON DIENTES.GRUPOS
(ID_GRUPO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.MATERIAL_PK ON DIENTES.MATERIAL
(ID_MATERIAL)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.MONEDAS_PK ON DIENTES.MONEDAS
(ID_MONEDA)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.PAISES_PK ON DIENTES.PAISES
(ID_PAIS)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.PERMISO_PK ON DIENTES.PERMISO
(ID_PERMISO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.TIPO_PAGOS_PK ON DIENTES.TIPO_PAGOS
(ID_TIPOPAGOS)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.TRATAMIENTO_PK ON DIENTES.TRATAMIENTO
(ID_TRATAMIENTO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DIENTES.CAMBIO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.CAMBIO CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.CAMBIO
(
  ID_MONEDA_1  INTEGER                          NOT NULL,
  ID_MONEDA_2  INTEGER                          NOT NULL,
  TIPO_CAMBIO  LONG                             NOT NULL,
  FECHA        DATE                             NOT NULL,
  ID_CAMBIO    INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.ESTADO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.ESTADO CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.ESTADO
(
  ID_ESTADO  INTEGER,
  NOMBRE     VARCHAR2(100 BYTE)                 NOT NULL,
  SIGLAS     VARCHAR2(3 BYTE)                   NOT NULL,
  ID_PAIS    INTEGER                            NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE DIENTES.GRUPO_PERMISO CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.GRUPO_PERMISO
(
  ID_GRUPO    INTEGER                           NOT NULL,
  ID_PERMISO  INTEGER                           NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DIENTES.CAMBIO_PK ON DIENTES.CAMBIO
(ID_CAMBIO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.ESTADO_PK ON DIENTES.ESTADO
(ID_ESTADO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DIENTES.CIUDADES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.CIUDADES CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.CIUDADES
(
  ID_CIUDAD  INTEGER,
  NOMBRE     VARCHAR2(100 BYTE)                 NOT NULL,
  SIGLAS     VARCHAR2(3 BYTE)                   NOT NULL,
  ID_ESTADO  INTEGER                            NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.DIRECCIONES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.DIRECCIONES CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.DIRECCIONES
(
  ID_DIRECCION  INTEGER,
  ID_CIUDAD     INTEGER                         NOT NULL,
  CALLE         VARCHAR2(100 BYTE)              NOT NULL,
  NUMERO        INTEGER                         NOT NULL,
  INFO_EXTRA    VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.USUARIOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.USUARIOS CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.USUARIOS
(
  ID_USUARIO    INTEGER,
  CONTRASENA    VARCHAR2(100 BYTE)              NOT NULL,
  USERNAME      VARCHAR2(100 BYTE)              NOT NULL,
  EMAIL         VARCHAR2(100 BYTE)              NOT NULL,
  NOMBRE        VARCHAR2(100 BYTE)              NOT NULL,
  CELULAR       VARCHAR2(100 BYTE)              NOT NULL,
  SEXO          VARCHAR2(1 BYTE)                NOT NULL,
  ID_DIRECCION  INTEGER                         NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DIENTES.CIUDADES_PK ON DIENTES.CIUDADES
(ID_CIUDAD)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.DIRECCIONES_PK ON DIENTES.DIRECCIONES
(ID_DIRECCION)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.USUARIOS_PK ON DIENTES.USUARIOS
(ID_USUARIO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DIENTES.DENTISTAS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.DENTISTAS CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.DENTISTAS
(
  ID_DENTISTA  INTEGER,
  ID_USUARIO   INTEGER                          NOT NULL,
  HORARIO      VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE DIENTES.ESPECIALIDAD_DENTISTA CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.ESPECIALIDAD_DENTISTA
(
  ID_ESPECIALIDAD  INTEGER                      NOT NULL,
  ID_DENTISTA      INTEGER                      NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.GRUPOS_USUARIO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.GRUPOS_USUARIO CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.GRUPOS_USUARIO
(
  ID_GRUPOSUSUARIO  INTEGER,
  ID_GRUPO          INTEGER                     NOT NULL,
  ID_USUARIO        INTEGER                     NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.PACIENTES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.PACIENTES CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.PACIENTES
(
  ID_PACIENTE          INTEGER,
  ID_USUARIO           INTEGER                  NOT NULL,
  CONTACTO_EMERGENCIA  VARCHAR2(100 BYTE),
  TIPO_SANGRE          VARCHAR2(5 BYTE)         NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE DIENTES.PACIENTE_ALERGIA CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.PACIENTE_ALERGIA
(
  ID_PACIENTE  INTEGER                          NOT NULL,
  ID_ALERGIA   INTEGER                          NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE DIENTES.PACIENTE_ENFERMEDAD CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.PACIENTE_ENFERMEDAD
(
  ID_PACIENTE    INTEGER                        NOT NULL,
  ID_ENFERMEDAD  INTEGER                        NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.PAGOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.PAGOS CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.PAGOS
(
  ID_PAGO       INTEGER,
  ID_DENTISTA   INTEGER                         NOT NULL,
  ID_PACIENTE   INTEGER                         NOT NULL,
  FECHA         DATE                            NOT NULL,
  TOTAL         LONG                            NOT NULL,
  ID_TIPOPAGOS  INTEGER                         NOT NULL,
  ID_CAMBIO     INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.TRATAMIENTO_PACIENTE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.TRATAMIENTO_PACIENTE CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.TRATAMIENTO_PACIENTE
(
  ID_TRATAMIENTOPACIENTE  INTEGER,
  ID_TRATAMIENTO          INTEGER               NOT NULL,
  ID_PACIENTE             INTEGER               NOT NULL,
  COSTO                   LONG,
  CITAS_NUMERO            INTEGER,
  CITAS_TOTAL             INTEGER,
  ABONOS_TOTALES          INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DIENTES.DENTISTAS_PK ON DIENTES.DENTISTAS
(ID_DENTISTA)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.GRUPOS_USUARIO_PK ON DIENTES.GRUPOS_USUARIO
(ID_GRUPOSUSUARIO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.PACIENTES_PK ON DIENTES.PACIENTES
(ID_PACIENTE)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.PAGOS_PK ON DIENTES.PAGOS
(ID_PAGO)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.TRATAMIENTO_PACIENTE_PK ON DIENTES.TRATAMIENTO_PACIENTE
(ID_TRATAMIENTOPACIENTE)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DIENTES.CITA
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.CITA CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.CITA
(
  ID_CITA      INTEGER,
  ID_PACIENTE  INTEGER                          NOT NULL,
  ID_DENTISTA  INTEGER                          NOT NULL,
  FECHA_HORA   DATE                             NOT NULL,
  DETALLE      VARCHAR2(100 BYTE)               NOT NULL,
  ASISTIO      CHAR(1 BYTE)                     NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE DIENTES.DETALLE_CITA
 DROP PRIMARY KEY CASCADE;

DROP TABLE DIENTES.DETALLE_CITA CASCADE CONSTRAINTS;

CREATE TABLE DIENTES.DETALLE_CITA
(
  ID_DETALLE_CITA         INTEGER,
  ID_CITA                 INTEGER               NOT NULL,
  ID_TRATAMIENTOPACIENTE  INTEGER               NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX DIENTES.CITA_PK ON DIENTES.CITA
(ID_CITA)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX DIENTES.DETALLE_CITA_PK ON DIENTES.DETALLE_CITA
(ID_DETALLE_CITA)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DIENTES.ALERGIAS ADD (
  CONSTRAINT ALERGIAS_PK
  PRIMARY KEY
  (ID_ALERGIA)
  USING INDEX DIENTES.ALERGIAS_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.ENFERMEDADES ADD (
  CONSTRAINT ENFERMEDADES_PK
  PRIMARY KEY
  (ID_ENFERMEDAD)
  USING INDEX DIENTES.ENFERMEDADES_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.ESPECIALIDADES ADD (
  CONSTRAINT ESPECIALIDADES_PK
  PRIMARY KEY
  (ID_ESPECIALIDAD)
  USING INDEX DIENTES.ESPECIALIDADES_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.GRUPOS ADD (
  CONSTRAINT GRUPOS_PK
  PRIMARY KEY
  (ID_GRUPO)
  USING INDEX DIENTES.GRUPOS_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.MATERIAL ADD (
  CONSTRAINT MATERIAL_PK
  PRIMARY KEY
  (ID_MATERIAL)
  USING INDEX DIENTES.MATERIAL_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.MONEDAS ADD (
  CONSTRAINT MONEDAS_PK
  PRIMARY KEY
  (ID_MONEDA)
  USING INDEX DIENTES.MONEDAS_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.PAISES ADD (
  CONSTRAINT PAISES_PK
  PRIMARY KEY
  (ID_PAIS)
  USING INDEX DIENTES.PAISES_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.PERMISO ADD (
  CONSTRAINT PERMISO_PK
  PRIMARY KEY
  (ID_PERMISO)
  USING INDEX DIENTES.PERMISO_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.TIPO_PAGOS ADD (
  CONSTRAINT TIPO_PAGOS_PK
  PRIMARY KEY
  (ID_TIPOPAGOS)
  USING INDEX DIENTES.TIPO_PAGOS_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.TRATAMIENTO ADD (
  CONSTRAINT TRATAMIENTO_PK
  PRIMARY KEY
  (ID_TRATAMIENTO)
  USING INDEX DIENTES.TRATAMIENTO_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.CAMBIO ADD (
  CONSTRAINT CAMBIO_PK
  PRIMARY KEY
  (ID_CAMBIO)
  USING INDEX DIENTES.CAMBIO_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.ESTADO ADD (
  CONSTRAINT ESTADO_PK
  PRIMARY KEY
  (ID_ESTADO)
  USING INDEX DIENTES.ESTADO_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.CIUDADES ADD (
  CONSTRAINT CIUDADES_PK
  PRIMARY KEY
  (ID_CIUDAD)
  USING INDEX DIENTES.CIUDADES_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.DIRECCIONES ADD (
  CONSTRAINT DIRECCIONES_PK
  PRIMARY KEY
  (ID_DIRECCION)
  USING INDEX DIENTES.DIRECCIONES_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.USUARIOS ADD (
  CONSTRAINT USUARIOS_PK
  PRIMARY KEY
  (ID_USUARIO)
  USING INDEX DIENTES.USUARIOS_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.DENTISTAS ADD (
  CONSTRAINT DENTISTAS_PK
  PRIMARY KEY
  (ID_DENTISTA)
  USING INDEX DIENTES.DENTISTAS_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.GRUPOS_USUARIO ADD (
  CONSTRAINT GRUPOS_USUARIO_PK
  PRIMARY KEY
  (ID_GRUPOSUSUARIO)
  USING INDEX DIENTES.GRUPOS_USUARIO_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.PACIENTES ADD (
  CONSTRAINT PACIENTES_PK
  PRIMARY KEY
  (ID_PACIENTE)
  USING INDEX DIENTES.PACIENTES_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.PAGOS ADD (
  CONSTRAINT PAGOS_PK
  PRIMARY KEY
  (ID_PAGO)
  USING INDEX DIENTES.PAGOS_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.TRATAMIENTO_PACIENTE ADD (
  CONSTRAINT TRATAMIENTO_PACIENTE_PK
  PRIMARY KEY
  (ID_TRATAMIENTOPACIENTE)
  USING INDEX DIENTES.TRATAMIENTO_PACIENTE_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.CITA ADD (
  CONSTRAINT CITA_PK
  PRIMARY KEY
  (ID_CITA)
  USING INDEX DIENTES.CITA_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.DETALLE_CITA ADD (
  CONSTRAINT DETALLE_CITA_PK
  PRIMARY KEY
  (ID_DETALLE_CITA)
  USING INDEX DIENTES.DETALLE_CITA_PK
  ENABLE VALIDATE);

ALTER TABLE DIENTES.TRATAMIENTO ADD (
  FOREIGN KEY (ID_ESPECIALIDAD) 
  REFERENCES DIENTES.ESPECIALIDADES
  ENABLE VALIDATE);

ALTER TABLE DIENTES.TRATAMIENTO_MATERIAL ADD (
  CONSTRAINT TRATAMIENTO_MATERIAL_R01 
  FOREIGN KEY (ID_TRATAMIENTO) 
  REFERENCES DIENTES.TRATAMIENTO
  ENABLE VALIDATE,
  CONSTRAINT TRATAMIENTO_MATERIAL_R02 
  FOREIGN KEY (ID_MATERIAL) 
  REFERENCES DIENTES.MATERIAL
  ENABLE VALIDATE);

ALTER TABLE DIENTES.CAMBIO ADD (
  CONSTRAINT CAMBIO_R01 
  FOREIGN KEY (ID_MONEDA_1) 
  REFERENCES DIENTES.MONEDAS
  ENABLE VALIDATE,
  CONSTRAINT CAMBIO_R02 
  FOREIGN KEY (ID_MONEDA_2) 
  REFERENCES DIENTES.MONEDAS
  ENABLE VALIDATE);

ALTER TABLE DIENTES.ESTADO ADD (
  FOREIGN KEY (ID_PAIS) 
  REFERENCES DIENTES.PAISES
  ENABLE VALIDATE);

ALTER TABLE DIENTES.GRUPO_PERMISO ADD (
  CONSTRAINT GRUPO_PERMISO_R01 
  FOREIGN KEY (ID_GRUPO) 
  REFERENCES DIENTES.GRUPOS
  ENABLE VALIDATE,
  CONSTRAINT GRUPO_PERMISO_R02 
  FOREIGN KEY (ID_PERMISO) 
  REFERENCES DIENTES.PERMISO
  ENABLE VALIDATE);

ALTER TABLE DIENTES.CIUDADES ADD (
  FOREIGN KEY (ID_ESTADO) 
  REFERENCES DIENTES.ESTADO
  ENABLE VALIDATE);

ALTER TABLE DIENTES.DIRECCIONES ADD (
  FOREIGN KEY (ID_CIUDAD) 
  REFERENCES DIENTES.CIUDADES
  ENABLE VALIDATE);

ALTER TABLE DIENTES.USUARIOS ADD (
  FOREIGN KEY (ID_DIRECCION) 
  REFERENCES DIENTES.DIRECCIONES
  ENABLE VALIDATE);

ALTER TABLE DIENTES.DENTISTAS ADD (
  CONSTRAINT DENTISTAS_R01 
  FOREIGN KEY (ID_USUARIO) 
  REFERENCES DIENTES.USUARIOS
  ENABLE VALIDATE);

ALTER TABLE DIENTES.ESPECIALIDAD_DENTISTA ADD (
  CONSTRAINT ESPECIALIDAD_DENTISTA_R01 
  FOREIGN KEY (ID_ESPECIALIDAD) 
  REFERENCES DIENTES.ESPECIALIDADES
  ENABLE VALIDATE,
  CONSTRAINT ESPECIALIDAD_DENTISTA_R02 
  FOREIGN KEY (ID_DENTISTA) 
  REFERENCES DIENTES.DENTISTAS
  ENABLE VALIDATE);

ALTER TABLE DIENTES.GRUPOS_USUARIO ADD (
  CONSTRAINT GRUPOS_USUARIO_R01 
  FOREIGN KEY (ID_GRUPO) 
  REFERENCES DIENTES.GRUPOS
  ENABLE VALIDATE,
  CONSTRAINT GRUPOS_USUARIO_R02 
  FOREIGN KEY (ID_USUARIO) 
  REFERENCES DIENTES.USUARIOS
  ENABLE VALIDATE);

ALTER TABLE DIENTES.PACIENTES ADD (
  CONSTRAINT PACIENTES_R01 
  FOREIGN KEY (ID_USUARIO) 
  REFERENCES DIENTES.USUARIOS
  ENABLE VALIDATE);

ALTER TABLE DIENTES.PACIENTE_ALERGIA ADD (
  CONSTRAINT PACIENTE_ALERGIA_R01 
  FOREIGN KEY (ID_PACIENTE) 
  REFERENCES DIENTES.PACIENTES
  ENABLE VALIDATE,
  CONSTRAINT PACIENTE_ALERGIA_R02 
  FOREIGN KEY (ID_ALERGIA) 
  REFERENCES DIENTES.ALERGIAS
  ENABLE VALIDATE);

ALTER TABLE DIENTES.PACIENTE_ENFERMEDAD ADD (
  CONSTRAINT PACIENTE_ENFERMEDAD_R01 
  FOREIGN KEY (ID_PACIENTE) 
  REFERENCES DIENTES.PACIENTES
  ENABLE VALIDATE,
  CONSTRAINT PACIENTE_ENFERMEDAD_R02 
  FOREIGN KEY (ID_ENFERMEDAD) 
  REFERENCES DIENTES.ENFERMEDADES
  ENABLE VALIDATE);

ALTER TABLE DIENTES.PAGOS ADD (
  CONSTRAINT PAGOS_R01 
  FOREIGN KEY (ID_DENTISTA) 
  REFERENCES DIENTES.DENTISTAS
  ENABLE VALIDATE,
  CONSTRAINT PAGOS_R02 
  FOREIGN KEY (ID_PACIENTE) 
  REFERENCES DIENTES.PACIENTES
  ENABLE VALIDATE,
  CONSTRAINT PAGOS_R03 
  FOREIGN KEY (ID_TIPOPAGOS) 
  REFERENCES DIENTES.TIPO_PAGOS
  ENABLE VALIDATE,
  CONSTRAINT PAGOS_R04 
  FOREIGN KEY (ID_CAMBIO) 
  REFERENCES DIENTES.CAMBIO
  ENABLE VALIDATE);

ALTER TABLE DIENTES.TRATAMIENTO_PACIENTE ADD (
  CONSTRAINT TRATAMIENTO_PACIENTE_R01 
  FOREIGN KEY (ID_TRATAMIENTO) 
  REFERENCES DIENTES.TRATAMIENTO
  ENABLE VALIDATE,
  CONSTRAINT TRATAMIENTO_PACIENTE_R02 
  FOREIGN KEY (ID_PACIENTE) 
  REFERENCES DIENTES.PACIENTES
  ENABLE VALIDATE);

ALTER TABLE DIENTES.CITA ADD (
  CONSTRAINT CITA_R01 
  FOREIGN KEY (ID_PACIENTE) 
  REFERENCES DIENTES.PACIENTES
  ENABLE VALIDATE,
  CONSTRAINT CITA_R02 
  FOREIGN KEY (ID_DENTISTA) 
  REFERENCES DIENTES.DENTISTAS
  ENABLE VALIDATE);

ALTER TABLE DIENTES.DETALLE_CITA ADD (
  CONSTRAINT DETALLE_CITA_R01 
  FOREIGN KEY (ID_CITA) 
  REFERENCES DIENTES.CITA
  ENABLE VALIDATE,
  CONSTRAINT DETALLE_CITA_R02 
  FOREIGN KEY (ID_TRATAMIENTOPACIENTE) 
  REFERENCES DIENTES.TRATAMIENTO_PACIENTE
  ENABLE VALIDATE);
