CREATE OR REPLACE PACKAGE BODY DIENTES.FUNCTIONALITY
AS
    FUNCTION CITA_REP(FECHA_2 IN DATE) RETURN NUMBER
    is
    CUENTA NUMBER;
    RESPUESTA NUMBER;
    BEGIN
        SELECT COUNT(*) INTO CUENTA FROM DIENTES.CITA CITAS WHERE CITAS.FECHA_HORA = FECHA_2;
        IF CUENTA > 0 THEN RESPUESTA := 0;
        ELSE RESPUESTA := 1;
        END IF;
        RETURN RESPUESTA;
        
    END CITA_REP;
END FUNCTIONALITY;
/