CREATE OR REPLACE PACKAGE BODY DIENTES.GET_PKG
AS
    PROCEDURE GET_PACIENTE_CITA(PACIENTE OUT SYS_REFCURSOR)
    AS
    BEGIN
    OPEN PACIENTE FOR
    SELECT paciente.ID,FIRST_NAME,LAST_NAME FROM DIENTES.AUTH_USER paciente
    LEFT JOIN DIENTES.AUTH_USER_GROUPS grupo ON paciente.ID = grupo.USER_ID WHERE grupo.USER_ID = NULL;
    END GET_PACIENTE_CITA;
END GET_PKG;
/