INSERT INTO DIENTES.ESPECIALIDADES especialidades (especialidades.ID_ESPECIALIDAD, especialidades.NOMBRE, especialidades.ACTIVO) VALUES (DIENTES.ESPECIALIDADES_SQ.NEXTVAL,  'Ortodoncista', 1);
INSERT INTO DIENTES.ESPECIALIDADES especialidades (especialidades.ID_ESPECIALIDAD, especialidades.NOMBRE, especialidades.ACTIVO) VALUES (DIENTES.ESPECIALIDADES_SQ.NEXTVAL,  'Endodoncista', 1);
INSERT INTO DIENTES.ESPECIALIDADES especialidades (especialidades.ID_ESPECIALIDAD, especialidades.NOMBRE, especialidades.ACTIVO) VALUES (DIENTES.ESPECIALIDADES_SQ.NEXTVAL,  'Periodoncista', 1);
INSERT INTO DIENTES.ESPECIALIDADES especialidades (especialidades.ID_ESPECIALIDAD, especialidades.NOMBRE, especialidades.ACTIVO) VALUES (DIENTES.ESPECIALIDADES_SQ.NEXTVAL,  'Cirujano maxilofacial', 1);
INSERT INTO DIENTES.ESPECIALIDADES especialidades (especialidades.ID_ESPECIALIDAD, especialidades.NOMBRE, especialidades.ACTIVO) VALUES (DIENTES.ESPECIALIDADES_SQ.NEXTVAL,  'Prostodoncista', 1);
INSERT INTO DIENTES.ESPECIALIDADES especialidades (especialidades.ID_ESPECIALIDAD, especialidades.NOMBRE, especialidades.ACTIVO) VALUES (DIENTES.ESPECIALIDADES_SQ.NEXTVAL,  'Patólogo Bucal', 1);
INSERT INTO DIENTES.ESPECIALIDADES especialidades (especialidades.ID_ESPECIALIDAD, especialidades.NOMBRE, especialidades.ACTIVO) VALUES (DIENTES.ESPECIALIDADES_SQ.NEXTVAL,  'Odontopediatra', 1);
INSERT INTO DIENTES.ESPECIALIDADES especialidades (especialidades.ID_ESPECIALIDAD, especialidades.NOMBRE, especialidades.ACTIVO) VALUES (DIENTES.ESPECIALIDADES_SQ.NEXTVAL,  'Cirujano Oral', 1);
